/* jshint node:true */
/*
 * grunt-webforge-js-testplate
 * https://github.com/pscheit/grunt-webforge-js-testplate
 *
 * Copyright (c) 2013 Philipp Scheit
 * Licensed under the MIT license.
 */

module.exports = function(grunt) {

  var getTemplateFile = function (name) {
    var path = require("path");

    if (grunt.file.exists('tests/'+name)) {
      return 'tests/'+name;
    } else if(grunt.file.exists())

    return __dirname + path.sep + 'config.file';
  };

  grunt.registerMultiTask("update-tests", "updates the index / and singleTestFiles (HTML) for all test files", function() {
    var filepaths = grunt.file.expand(grunt.util._.pluck(this.files, 'src'));
    var _ = grunt.util._;
    
    // all files are relative to the grunt.js file
    grunt.log.writeln("found "+filepaths.length+" testfiles.");
    grunt.file.write(
      "tests/all.js",
      
      "/* This file was auto-generated by grunt update-tests-task on "+grunt.template.today("yyyy-mm-dd hh:mm")+" */\n"+
      "define(function () {\n"+
      "  return "+JSON.stringify(
        _.map(filepaths, function (path) { return '/'+path; }),
        undefined,
        2
      )+";\n"+
      "});\n"
    );
    
    var testCode = _.template(grunt.file.read(getTemplateFile('TestTemplate.html')));
    
    // write SinlgeTests
    _.each(filepaths, function(path) {
      var htmlPath = path.replace(/^(.*?)\.js$/, "$1.html");
      var test = path.match(/^tests\/(.*?)Test\.js$/)[1];
      
      grunt.log.writeln("write single test ("+test+") File for "+path+" to "+htmlPath);
      
      grunt.file.write(htmlPath, testCode({
        testTitle: 'single test for: '+test.replace('/\/g', '.'),
        testName: test+"Test"
      }));
    });
    
    grunt.log.ok();
  });
};