/* This file was auto-generated by grunt update-tests-task on 2013-07-11 09:07 */
define(function () {
  return [
  "/tests/Cojoko/Experiments/JooseClassParserTest.js",
  "/tests/Cojoko/Experiments/JooseClassReaderTest.js"
];
});
