/* This file was auto-generated by grunt update-tests-task on 2013-07-22 03:07 */
define(function () {
  return [
  "/tests/Cojoko/Experiments/JooseAllTest.js",
  "/tests/Cojoko/Experiments/JooseClassParserTest.js",
  "/tests/Cojoko/JooseClassReaderTest.js",
  "/tests/Cojoko/WriterTest.js"
];
});
